// Code generated by mcpgen; DO NOT EDIT.

package mcp

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	mcpsdk "github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerGeneratedTools wires every spec-derived MCP tool onto s.mcp.
// Called from registerTools() in tools.go.
func (s *Server) registerGeneratedTools() {
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every season in the API's history (starts from 1876 for\nsportId=1). divisionId / leagueId are supported here when the\ntoddrob99 `all` path is used.",
		Name:        "mlb_get_all_seasons",
	}, s.toolGetAllSeasons)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "All-Star ballot",
		Name:        "mlb_get_all_star_ballot",
	}, s.toolGetAllStarBallot)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "All-Star final vote",
		Name:        "mlb_get_all_star_final_vote",
	}, s.toolGetAllStarFinalVote)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "All-Star write-ins",
		Name:        "mlb_get_all_star_write_ins",
	}, s.toolGetAllStarWriteIns)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns per-season attendance records. toddrob99 marks\nrequired_params=[[\"teamId\"], [\"leagueId\"], [\"leagueListId\"]] —\none of TeamID, LeagueID, or LeagueListID must be set. The SDK\nenforces this with an ErrInvalidQuery runtime check.",
		Name:        "mlb_get_attendance",
	}, s.toolGetAttendance)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every recipient of the given award (e.g. MLBHOF, MVP).\ntoddrob99 models awardId as an optional path-param — the SDK\nrequires it (the no-path-arg form, which lists every award id,\nis exposed separately).",
		Name:        "mlb_get_award_recipients",
	}, s.toolGetAwardRecipients)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "List conferences",
		Name:        "mlb_get_conferences",
	}, s.toolGetConferences)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Context metrics (win probability, sac fly probability) for a game",
		Name:        "mlb_get_context_metrics",
	}, s.toolGetContextMetrics)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns a list of divisions. Calling with no query parameters returns\nevery division the MLB API tracks (MLB, minor leagues, college,\netc.). Filter via divisionId, leagueId, sportId, or season.",
		Name:        "mlb_get_divisions",
	}, s.toolGetDivisions)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns draft data for a given year. The response wraps rounds and\npicks with rich person/team/school sub-objects.",
		Name:        "mlb_get_draft",
	}, s.toolGetDraft)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns schedule-like data for games modified since a given\ntimestamp. toddrob99 marks updatedSince as required.",
		Name:        "mlb_get_game_changes",
	}, s.toolGetGameChanges)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Color commentary feed for a game",
		Name:        "mlb_get_game_color",
	}, s.toolGetGameColor)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Color feed diff patch",
		Name:        "mlb_get_game_color_diff",
	}, s.toolGetGameColorDiff)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Color-feed timestamps for a live game",
		Name:        "mlb_get_game_color_timestamps",
	}, s.toolGetGameColorTimestamps)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Game content (highlights, editorial)",
		Name:        "mlb_get_game_content",
	}, s.toolGetGameContent)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Live feed diff patch",
		Name:        "mlb_get_game_diff",
	}, s.toolGetGameDiff)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns pace-of-play stats for a sport + season. toddrob99\nmarks season as required. The response wraps data under\n`{sports: [...]}`.",
		Name:        "mlb_get_game_pace",
	}, s.toolGetGamePace)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Feed timestamps for a live game",
		Name:        "mlb_get_game_timestamps",
	}, s.toolGetGameTimestamps)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Uniform data for games",
		Name:        "mlb_get_game_uniforms",
	}, s.toolGetGameUniforms)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Win probability per at-bat",
		Name:        "mlb_get_game_win_probability",
	}, s.toolGetGameWinProbability)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns high/low stat leaders. orgType is one of player, team,\ndivision, league, sport, types. toddrob99 marks sortStat+season\nas required together.",
		Name:        "mlb_get_high_low",
	}, s.toolGetHighLow)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Home Run Derby data",
		Name:        "mlb_get_home_run_derby",
	}, s.toolGetHomeRunDerby)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Staff by job type",
		Name:        "mlb_get_jobs",
	}, s.toolGetJobs)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Datacaster roster",
		Name:        "mlb_get_jobs_datacasters",
	}, s.toolGetJobsDatacasters)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Official scorer roster",
		Name:        "mlb_get_jobs_official_scorers",
	}, s.toolGetJobsOfficialScorers)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Umpire roster",
		Name:        "mlb_get_jobs_umpires",
	}, s.toolGetJobsUmpires)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns the leagues the MLB API tracks. The toddrob99 catalog\nmarks `sportId` or `leagueIds` as required (one-of). The SDK\nenforces this with an ErrInvalidQuery runtime check.",
		Name:        "mlb_get_leagues",
	}, s.toolGetLeagues)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Full live game feed (v1.1)",
		Name:        "mlb_get_live_feed",
	}, s.toolGetLiveFeed)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "API metadata (gameTypes, statGroups, etc.)",
		Name:        "mlb_get_meta",
	}, s.toolGetMeta)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns metadata for one or more people. personIds is required.",
		Name:        "mlb_get_people",
	}, s.toolGetPeople)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Recently changed person records",
		Name:        "mlb_get_people_changes",
	}, s.toolGetPeopleChanges)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Player stats for a specific game",
		Name:        "mlb_get_person_game_stats",
	}, s.toolGetPersonGameStats)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Play-by-play for a single game (v1)",
		Name:        "mlb_get_play_by_play",
	}, s.toolGetPlayByPlay)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Postseason series",
		Name:        "mlb_get_schedule_postseason_series",
	}, s.toolGetSchedulePostseasonSeries)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Postseason tune-in info",
		Name:        "mlb_get_schedule_postseason_tune_in",
	}, s.toolGetSchedulePostseasonTuneIn)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Tied/suspended games for a season",
		Name:        "mlb_get_schedule_tied",
	}, s.toolGetScheduleTied)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns metadata for one season. sportId is required by the MLB API\n(and encoded as `required_params: [[\"sportId\"]]` in toddrob99). The\nresponse is a `{\"seasons\": [...]}` array of one element; the SDK\ncollapses it to *Season and maps an empty array to ErrNotFound.",
		Name:        "mlb_get_season",
	}, s.toolGetSeason)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns season metadata. At least one of sportId, divisionId, or\nleagueId is required (the toddrob99 catalog encodes this as\n`required_params: [[\"sportId\"], [\"divisionId\"], [\"leagueId\"]]`). To\nquery the full history of seasons, use the `/api/v1/seasons/all`\npath instead (see getAllSeasons).",
		Name:        "mlb_get_seasons",
	}, s.toolGetSeasons)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every sport the MLB Stats API exposes (MLB, AAA, AA, …) when\ncalled with no parameters. Filter to a single sport via sportId.",
		Name:        "mlb_get_sports",
	}, s.toolGetSports)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "All players for a sport + season",
		Name:        "mlb_get_sports_players",
	}, s.toolGetSportsPlayers)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "League-wide individual stats",
		Name:        "mlb_get_stats",
	}, s.toolGetStats)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns hitting/pitching streak data. toddrob99 marks streakType,\nstreakSpan, season, sportId, and limit as all required together.\nNote: this endpoint may return 404 during the offseason.",
		Name:        "mlb_get_stats_streaks",
	}, s.toolGetStatsStreaks)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Team alumni",
		Name:        "mlb_get_team_alumni",
	}, s.toolGetTeamAlumni)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Coaching staff for a team",
		Name:        "mlb_get_team_coaches",
	}, s.toolGetTeamCoaches)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Team stat leaders",
		Name:        "mlb_get_team_leaders",
	}, s.toolGetTeamLeaders)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Front-office personnel for a team",
		Name:        "mlb_get_team_personnel",
	}, s.toolGetTeamPersonnel)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Aggregated team stats",
		Name:        "mlb_get_team_stats",
	}, s.toolGetTeamStats)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Team uniform catalog",
		Name:        "mlb_get_team_uniforms",
	}, s.toolGetTeamUniforms)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns every team the MLB API tracks when called with no filters.\nFilter by sport, league(s), and season. Hydrate sub-objects via\nthe hydrate query parameter as documented on /teams/{teamId}.",
		Name:        "mlb_get_teams",
	}, s.toolGetTeams)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Affiliate teams for given team ids",
		Name:        "mlb_get_teams_affiliates",
	}, s.toolGetTeamsAffiliates)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Historical team records",
		Name:        "mlb_get_teams_history",
	}, s.toolGetTeamsHistory)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "League-wide team stats",
		Name:        "mlb_get_teams_stats",
	}, s.toolGetTeamsStats)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Games assigned to an umpire",
		Name:        "mlb_get_umpire_games",
	}, s.toolGetUmpireGames)
	mcpsdk.AddTool(s.mcp, &mcpsdk.Tool{
		Description: "Returns metadata for a single venue. The MLB API also accepts a\ncomma-separated `venueIds` query parameter at `/api/v1/venues`, but\nthis SDK exposes the path-based single-object lookup form.",
		Name:        "mlb_get_venue",
	}, s.toolGetVenue)
}

type getAllSeasonsArgs struct {
	SportId    int    `json:"sportId,omitempty"`
	DivisionId int    `json:"divisionId,omitempty"`
	LeagueId   int    `json:"leagueId,omitempty"`
	Fields     string `json:"fields,omitempty"`
}

func (s *Server) toolGetAllSeasons(ctx context.Context, _ *mcpsdk.CallToolRequest, args getAllSeasonsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/seasons/all"
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.DivisionId != 0 {
		qv.Set("divisionId", fmt.Sprintf("%d", args.DivisionId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_seasons: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_seasons: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_seasons: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_all_seasons: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getAllStarBallotArgs struct {
	LeagueId int    `json:"leagueId"`
	Season   int    `json:"season"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetAllStarBallot(ctx context.Context, _ *mcpsdk.CallToolRequest, args getAllStarBallotArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/league/{leagueId}/allStarBallot"
	u = strings.Replace(u, "{leagueId}", fmt.Sprintf("%d", args.LeagueId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_ballot: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_ballot: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_ballot: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_all_star_ballot: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getAllStarFinalVoteArgs struct {
	LeagueId int    `json:"leagueId"`
	Season   int    `json:"season"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetAllStarFinalVote(ctx context.Context, _ *mcpsdk.CallToolRequest, args getAllStarFinalVoteArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/league/{leagueId}/allStarFinalVote"
	u = strings.Replace(u, "{leagueId}", fmt.Sprintf("%d", args.LeagueId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_final_vote: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_final_vote: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_final_vote: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_all_star_final_vote: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getAllStarWriteInsArgs struct {
	LeagueId int    `json:"leagueId"`
	Season   int    `json:"season"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetAllStarWriteIns(ctx context.Context, _ *mcpsdk.CallToolRequest, args getAllStarWriteInsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/league/{leagueId}/allStarWriteIns"
	u = strings.Replace(u, "{leagueId}", fmt.Sprintf("%d", args.LeagueId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_write_ins: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_write_ins: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_all_star_write_ins: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_all_star_write_ins: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getAttendanceArgs struct {
	TeamId       int    `json:"teamId,omitempty"`
	LeagueId     int    `json:"leagueId,omitempty"`
	Season       int    `json:"season,omitempty"`
	Date         string `json:"date,omitempty" jsonschema:"YYYY-MM-DD"`
	LeagueListId string `json:"leagueListId,omitempty" jsonschema:"e.g. milb_all"`
	GameType     string `json:"gameType,omitempty" jsonschema:"R | S | E | A | D | F | L | W"`
	Fields       string `json:"fields,omitempty"`
}

func (s *Server) toolGetAttendance(ctx context.Context, _ *mcpsdk.CallToolRequest, args getAttendanceArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/attendance"
	qv := url.Values{}
	if args.TeamId != 0 {
		qv.Set("teamId", fmt.Sprintf("%d", args.TeamId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Date != "" {
		qv.Set("date", args.Date)
	}
	if args.LeagueListId != "" {
		qv.Set("leagueListId", args.LeagueListId)
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_attendance: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_attendance: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_attendance: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_attendance: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getAwardRecipientsArgs struct {
	AwardId  string `json:"awardId" jsonschema:"e.g. MLBHOF, ALMVP"`
	SportId  int    `json:"sportId,omitempty"`
	LeagueId int    `json:"leagueId,omitempty"`
	Season   int    `json:"season,omitempty"`
	Hydrate  string `json:"hydrate,omitempty"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetAwardRecipients(ctx context.Context, _ *mcpsdk.CallToolRequest, args getAwardRecipientsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/awards/{awardId}/recipients"
	u = strings.Replace(u, "{awardId}", args.AwardId, 1)
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_award_recipients: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_award_recipients: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_award_recipients: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_award_recipients: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getConferencesArgs struct {
	ConferenceId int    `json:"conferenceId,omitempty"`
	Season       int    `json:"season,omitempty"`
	Fields       string `json:"fields,omitempty"`
}

func (s *Server) toolGetConferences(ctx context.Context, _ *mcpsdk.CallToolRequest, args getConferencesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/conferences"
	qv := url.Values{}
	if args.ConferenceId != 0 {
		qv.Set("conferenceId", fmt.Sprintf("%d", args.ConferenceId))
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_conferences: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_conferences: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_conferences: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_conferences: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getContextMetricsArgs struct {
	GamePk   int    `json:"gamePk"`
	Timecode string `json:"timecode,omitempty"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetContextMetrics(ctx context.Context, _ *mcpsdk.CallToolRequest, args getContextMetricsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/contextMetrics"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.Timecode != "" {
		qv.Set("timecode", args.Timecode)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_context_metrics: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_context_metrics: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_context_metrics: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_context_metrics: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getDivisionsArgs struct {
	DivisionId int `json:"divisionId,omitempty"`
	LeagueId   int `json:"leagueId,omitempty"`
	SportId    int `json:"sportId,omitempty" jsonschema:"1 = MLB"`
	Season     int `json:"season,omitempty"`
}

func (s *Server) toolGetDivisions(ctx context.Context, _ *mcpsdk.CallToolRequest, args getDivisionsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/divisions"
	qv := url.Values{}
	if args.DivisionId != 0 {
		qv.Set("divisionId", fmt.Sprintf("%d", args.DivisionId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_divisions: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_divisions: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_divisions: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_divisions: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getDraftArgs struct {
	Year   int    `json:"year"`
	Round  string `json:"round,omitempty"`
	Fields string `json:"fields,omitempty"`
}

func (s *Server) toolGetDraft(ctx context.Context, _ *mcpsdk.CallToolRequest, args getDraftArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/draft/{year}"
	u = strings.Replace(u, "{year}", fmt.Sprintf("%d", args.Year), 1)
	qv := url.Values{}
	if args.Round != "" {
		qv.Set("round", args.Round)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_draft: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_draft: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_draft: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_draft: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameChangesArgs struct {
	UpdatedSince string `json:"updatedSince" jsonschema:"ISO-8601 timestamp"`
	SportId      int    `json:"sportId,omitempty"`
	GameType     string `json:"gameType,omitempty"`
	Season       int    `json:"season,omitempty"`
	Fields       string `json:"fields,omitempty"`
}

func (s *Server) toolGetGameChanges(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameChangesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/changes"
	qv := url.Values{}
	if args.UpdatedSince != "" {
		qv.Set("updatedSince", args.UpdatedSince)
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_changes: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_changes: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_changes: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_changes: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameColorArgs struct {
	GamePk   int    `json:"gamePk"`
	Timecode string `json:"timecode,omitempty"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetGameColor(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameColorArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/feed/color"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.Timecode != "" {
		qv.Set("timecode", args.Timecode)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_color: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameColorDiffArgs struct {
	GamePk        int    `json:"gamePk"`
	StartTimecode string `json:"startTimecode"`
	EndTimecode   string `json:"endTimecode"`
}

func (s *Server) toolGetGameColorDiff(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameColorDiffArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/feed/color/diffPatch"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.StartTimecode != "" {
		qv.Set("startTimecode", args.StartTimecode)
	}
	if args.EndTimecode != "" {
		qv.Set("endTimecode", args.EndTimecode)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color_diff: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color_diff: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color_diff: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_color_diff: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameColorTimestampsArgs struct {
	GamePk int `json:"gamePk"`
}

func (s *Server) toolGetGameColorTimestamps(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameColorTimestampsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/feed/color/timestamps"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color_timestamps: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color_timestamps: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_color_timestamps: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_color_timestamps: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameContentArgs struct {
	GamePk         int `json:"gamePk"`
	HighlightLimit int `json:"highlightLimit,omitempty"`
}

func (s *Server) toolGetGameContent(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameContentArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/content"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.HighlightLimit != 0 {
		qv.Set("highlightLimit", fmt.Sprintf("%d", args.HighlightLimit))
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_content: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_content: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_content: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_content: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameDiffArgs struct {
	GamePk        int    `json:"gamePk"`
	StartTimecode string `json:"startTimecode"`
	EndTimecode   string `json:"endTimecode"`
}

func (s *Server) toolGetGameDiff(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameDiffArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/feed/live/diffPatch"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.StartTimecode != "" {
		qv.Set("startTimecode", args.StartTimecode)
	}
	if args.EndTimecode != "" {
		qv.Set("endTimecode", args.EndTimecode)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_diff: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_diff: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_diff: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_diff: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGamePaceArgs struct {
	Season          int    `json:"season"`
	SportId         int    `json:"sportId,omitempty"`
	TeamIds         string `json:"teamIds,omitempty"`
	LeagueIds       string `json:"leagueIds,omitempty"`
	LeagueListId    string `json:"leagueListId,omitempty"`
	GameType        string `json:"gameType,omitempty"`
	StartDate       string `json:"startDate,omitempty"`
	EndDate         string `json:"endDate,omitempty"`
	VenueIds        string `json:"venueIds,omitempty"`
	OrgType         string `json:"orgType,omitempty"`
	IncludeChildren bool   `json:"includeChildren,omitempty"`
	Fields          string `json:"fields,omitempty"`
}

func (s *Server) toolGetGamePace(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGamePaceArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/gamePace"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.TeamIds != "" {
		qv.Set("teamIds", args.TeamIds)
	}
	if args.LeagueIds != "" {
		qv.Set("leagueIds", args.LeagueIds)
	}
	if args.LeagueListId != "" {
		qv.Set("leagueListId", args.LeagueListId)
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.StartDate != "" {
		qv.Set("startDate", args.StartDate)
	}
	if args.EndDate != "" {
		qv.Set("endDate", args.EndDate)
	}
	if args.VenueIds != "" {
		qv.Set("venueIds", args.VenueIds)
	}
	if args.OrgType != "" {
		qv.Set("orgType", args.OrgType)
	}
	if args.IncludeChildren {
		qv.Set("includeChildren", "true")
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_pace: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_pace: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_pace: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_pace: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameTimestampsArgs struct {
	GamePk int `json:"gamePk"`
}

func (s *Server) toolGetGameTimestamps(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameTimestampsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/feed/live/timestamps"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_timestamps: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_timestamps: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_timestamps: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_timestamps: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameUniformsArgs struct {
	GamePks string `json:"gamePks" jsonschema:"comma-separated game pks"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetGameUniforms(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameUniformsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/uniforms/game"
	qv := url.Values{}
	if args.GamePks != "" {
		qv.Set("gamePks", args.GamePks)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_uniforms: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_uniforms: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_uniforms: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_uniforms: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getGameWinProbabilityArgs struct {
	GamePk   int    `json:"gamePk"`
	Timecode string `json:"timecode,omitempty"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetGameWinProbability(ctx context.Context, _ *mcpsdk.CallToolRequest, args getGameWinProbabilityArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/winProbability"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.Timecode != "" {
		qv.Set("timecode", args.Timecode)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_win_probability: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_win_probability: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_game_win_probability: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_game_win_probability: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getHighLowArgs struct {
	OrgType   string `json:"orgType" jsonschema:"player | team | division | league | sport | types"`
	SortStat  string `json:"sortStat,omitempty" jsonschema:"e.g. homeRuns, hits, strikeOuts"`
	Season    int    `json:"season,omitempty"`
	GameType  string `json:"gameType,omitempty"`
	TeamId    int    `json:"teamId,omitempty"`
	LeagueId  int    `json:"leagueId,omitempty"`
	SportIds  string `json:"sportIds,omitempty"`
	StatGroup string `json:"statGroup,omitempty"`
	Limit     int    `json:"limit,omitempty"`
	Fields    string `json:"fields,omitempty"`
}

func (s *Server) toolGetHighLow(ctx context.Context, _ *mcpsdk.CallToolRequest, args getHighLowArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/highLow/{orgType}"
	u = strings.Replace(u, "{orgType}", args.OrgType, 1)
	qv := url.Values{}
	if args.SortStat != "" {
		qv.Set("sortStat", args.SortStat)
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.TeamId != 0 {
		qv.Set("teamId", fmt.Sprintf("%d", args.TeamId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.SportIds != "" {
		qv.Set("sportIds", args.SportIds)
	}
	if args.StatGroup != "" {
		qv.Set("statGroup", args.StatGroup)
	}
	if args.Limit != 0 {
		qv.Set("limit", fmt.Sprintf("%d", args.Limit))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_high_low: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_high_low: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_high_low: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_high_low: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getHomeRunDerbyArgs struct {
	GamePk int    `json:"gamePk"`
	Fields string `json:"fields,omitempty"`
}

func (s *Server) toolGetHomeRunDerby(ctx context.Context, _ *mcpsdk.CallToolRequest, args getHomeRunDerbyArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/homeRunDerby/{gamePk}"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_home_run_derby: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_home_run_derby: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_home_run_derby: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_home_run_derby: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getJobsArgs struct {
	JobType string `json:"jobType" jsonschema:"e.g. UMPR, SCOR, DCST"`
	SportId int    `json:"sportId,omitempty"`
	Date    string `json:"date,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetJobs(ctx context.Context, _ *mcpsdk.CallToolRequest, args getJobsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/jobs"
	qv := url.Values{}
	if args.JobType != "" {
		qv.Set("jobType", args.JobType)
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Date != "" {
		qv.Set("date", args.Date)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_jobs: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getJobsDatacastersArgs struct {
	SportId int    `json:"sportId,omitempty"`
	Date    string `json:"date,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetJobsDatacasters(ctx context.Context, _ *mcpsdk.CallToolRequest, args getJobsDatacastersArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/jobs/datacasters"
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Date != "" {
		qv.Set("date", args.Date)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_datacasters: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_datacasters: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_datacasters: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_jobs_datacasters: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getJobsOfficialScorersArgs struct {
	Timecode string `json:"timecode,omitempty"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetJobsOfficialScorers(ctx context.Context, _ *mcpsdk.CallToolRequest, args getJobsOfficialScorersArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/jobs/officialScorers"
	qv := url.Values{}
	if args.Timecode != "" {
		qv.Set("timecode", args.Timecode)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_official_scorers: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_official_scorers: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_official_scorers: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_jobs_official_scorers: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getJobsUmpiresArgs struct {
	SportId int    `json:"sportId,omitempty"`
	Date    string `json:"date,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetJobsUmpires(ctx context.Context, _ *mcpsdk.CallToolRequest, args getJobsUmpiresArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/jobs/umpires"
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Date != "" {
		qv.Set("date", args.Date)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_umpires: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_umpires: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_jobs_umpires: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_jobs_umpires: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getLeaguesArgs struct {
	SportId   int    `json:"sportId,omitempty" jsonschema:"1 = MLB"`
	LeagueIds string `json:"leagueIds,omitempty" jsonschema:"comma-separated league ids"`
	Seasons   string `json:"seasons,omitempty" jsonschema:"comma-separated seasons"`
	Fields    string `json:"fields,omitempty"`
}

func (s *Server) toolGetLeagues(ctx context.Context, _ *mcpsdk.CallToolRequest, args getLeaguesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/league"
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.LeagueIds != "" {
		qv.Set("leagueIds", args.LeagueIds)
	}
	if args.Seasons != "" {
		qv.Set("seasons", args.Seasons)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_leagues: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_leagues: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_leagues: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_leagues: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getLiveFeedArgs struct {
	GamePk int `json:"gamePk"`
}

func (s *Server) toolGetLiveFeed(ctx context.Context, _ *mcpsdk.CallToolRequest, args getLiveFeedArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1.1/game/{gamePk}/feed/live"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_live_feed: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_live_feed: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_live_feed: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_live_feed: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getMetaArgs struct {
	MetaType string `json:"metaType" jsonschema:"e.g. gameTypes, statGroups, eventTypes"`
}

func (s *Server) toolGetMeta(ctx context.Context, _ *mcpsdk.CallToolRequest, args getMetaArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/{metaType}"
	u = strings.Replace(u, "{metaType}", args.MetaType, 1)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_meta: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_meta: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_meta: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_meta: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getPeopleArgs struct {
	PersonIds string `json:"personIds" jsonschema:"comma-separated person ids"`
	Hydrate   string `json:"hydrate,omitempty"`
	Fields    string `json:"fields,omitempty"`
}

func (s *Server) toolGetPeople(ctx context.Context, _ *mcpsdk.CallToolRequest, args getPeopleArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/people"
	qv := url.Values{}
	if args.PersonIds != "" {
		qv.Set("personIds", args.PersonIds)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_people: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_people: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_people: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_people: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getPeopleChangesArgs struct {
	UpdatedSince string `json:"updatedSince,omitempty"`
	Fields       string `json:"fields,omitempty"`
}

func (s *Server) toolGetPeopleChanges(ctx context.Context, _ *mcpsdk.CallToolRequest, args getPeopleChangesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/people/changes"
	qv := url.Values{}
	if args.UpdatedSince != "" {
		qv.Set("updatedSince", args.UpdatedSince)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_people_changes: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_people_changes: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_people_changes: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_people_changes: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getPersonGameStatsArgs struct {
	PersonId int    `json:"personId"`
	GamePk   int    `json:"gamePk"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetPersonGameStats(ctx context.Context, _ *mcpsdk.CallToolRequest, args getPersonGameStatsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/people/{personId}/stats/game/{gamePk}"
	u = strings.Replace(u, "{personId}", fmt.Sprintf("%d", args.PersonId), 1)
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	qv := url.Values{}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_person_game_stats: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_person_game_stats: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_person_game_stats: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_person_game_stats: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getPlayByPlayArgs struct {
	GamePk int `json:"gamePk"`
}

func (s *Server) toolGetPlayByPlay(ctx context.Context, _ *mcpsdk.CallToolRequest, args getPlayByPlayArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/game/{gamePk}/playByPlay"
	u = strings.Replace(u, "{gamePk}", fmt.Sprintf("%d", args.GamePk), 1)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_play_by_play: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_play_by_play: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_play_by_play: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_play_by_play: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getSchedulePostseasonSeriesArgs struct {
	Season       int    `json:"season,omitempty"`
	GameTypes    string `json:"gameTypes,omitempty"`
	SeriesNumber int    `json:"seriesNumber,omitempty"`
	TeamId       int    `json:"teamId,omitempty"`
	SportId      int    `json:"sportId,omitempty"`
	Fields       string `json:"fields,omitempty"`
}

func (s *Server) toolGetSchedulePostseasonSeries(ctx context.Context, _ *mcpsdk.CallToolRequest, args getSchedulePostseasonSeriesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/schedule/postseason/series"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.GameTypes != "" {
		qv.Set("gameTypes", args.GameTypes)
	}
	if args.SeriesNumber != 0 {
		qv.Set("seriesNumber", fmt.Sprintf("%d", args.SeriesNumber))
	}
	if args.TeamId != 0 {
		qv.Set("teamId", fmt.Sprintf("%d", args.TeamId))
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_series: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_series: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_series: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_series: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getSchedulePostseasonTuneInArgs struct {
	Season  int    `json:"season,omitempty"`
	TeamId  int    `json:"teamId,omitempty"`
	SportId int    `json:"sportId,omitempty"`
	Hydrate string `json:"hydrate,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetSchedulePostseasonTuneIn(ctx context.Context, _ *mcpsdk.CallToolRequest, args getSchedulePostseasonTuneInArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/schedule/postseason/tuneIn"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.TeamId != 0 {
		qv.Set("teamId", fmt.Sprintf("%d", args.TeamId))
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_tune_in: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_tune_in: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_tune_in: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_schedule_postseason_tune_in: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getScheduleTiedArgs struct {
	Season    int    `json:"season"`
	GameTypes string `json:"gameTypes,omitempty"`
	Hydrate   string `json:"hydrate,omitempty"`
	Fields    string `json:"fields,omitempty"`
}

func (s *Server) toolGetScheduleTied(ctx context.Context, _ *mcpsdk.CallToolRequest, args getScheduleTiedArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/schedule/games/tied"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.GameTypes != "" {
		qv.Set("gameTypes", args.GameTypes)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_tied: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_tied: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_schedule_tied: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_schedule_tied: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getSeasonArgs struct {
	SeasonId string `json:"seasonId" jsonschema:"e.g. 2024"`
	SportId  int    `json:"sportId" jsonschema:"1 = MLB"`
	Fields   string `json:"fields,omitempty" jsonschema:"comma-separated field projection"`
}

func (s *Server) toolGetSeason(ctx context.Context, _ *mcpsdk.CallToolRequest, args getSeasonArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/seasons/{seasonId}"
	u = strings.Replace(u, "{seasonId}", args.SeasonId, 1)
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_season: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_season: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_season: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_season: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getSeasonsArgs struct {
	Season     int    `json:"season,omitempty"`
	SportId    int    `json:"sportId,omitempty"`
	DivisionId int    `json:"divisionId,omitempty"`
	LeagueId   int    `json:"leagueId,omitempty"`
	Fields     string `json:"fields,omitempty" jsonschema:"comma-separated field projection"`
}

func (s *Server) toolGetSeasons(ctx context.Context, _ *mcpsdk.CallToolRequest, args getSeasonsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/seasons"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.DivisionId != 0 {
		qv.Set("divisionId", fmt.Sprintf("%d", args.DivisionId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_seasons: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_seasons: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_seasons: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_seasons: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getSportsArgs struct {
	SportId int    `json:"sportId,omitempty" jsonschema:"1 = MLB"`
	Fields  string `json:"fields,omitempty" jsonschema:"comma-separated field projection"`
}

func (s *Server) toolGetSports(ctx context.Context, _ *mcpsdk.CallToolRequest, args getSportsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/sports"
	qv := url.Values{}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_sports: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_sports: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_sports: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_sports: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getSportsPlayersArgs struct {
	SportId  int    `json:"sportId"`
	Season   int    `json:"season"`
	GameType string `json:"gameType,omitempty"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetSportsPlayers(ctx context.Context, _ *mcpsdk.CallToolRequest, args getSportsPlayersArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/sports/{sportId}/players"
	u = strings.Replace(u, "{sportId}", fmt.Sprintf("%d", args.SportId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_sports_players: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_sports_players: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_sports_players: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_sports_players: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getStatsArgs struct {
	Stats      string `json:"stats"`
	Group      string `json:"group"`
	Season     int    `json:"season,omitempty"`
	SportIds   string `json:"sportIds,omitempty"`
	GameType   string `json:"gameType,omitempty"`
	PlayerPool string `json:"playerPool,omitempty"`
	Position   string `json:"position,omitempty"`
	TeamId     int    `json:"teamId,omitempty"`
	LeagueId   int    `json:"leagueId,omitempty"`
	PersonId   int    `json:"personId,omitempty"`
	Limit      int    `json:"limit,omitempty"`
	Offset     int    `json:"offset,omitempty"`
	SortStat   string `json:"sortStat,omitempty"`
	Order      string `json:"order,omitempty"`
	Metrics    string `json:"metrics,omitempty"`
	StartDate  string `json:"startDate,omitempty"`
	EndDate    string `json:"endDate,omitempty"`
	Hydrate    string `json:"hydrate,omitempty"`
	Fields     string `json:"fields,omitempty"`
}

func (s *Server) toolGetStats(ctx context.Context, _ *mcpsdk.CallToolRequest, args getStatsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/stats"
	qv := url.Values{}
	if args.Stats != "" {
		qv.Set("stats", args.Stats)
	}
	if args.Group != "" {
		qv.Set("group", args.Group)
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.SportIds != "" {
		qv.Set("sportIds", args.SportIds)
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.PlayerPool != "" {
		qv.Set("playerPool", args.PlayerPool)
	}
	if args.Position != "" {
		qv.Set("position", args.Position)
	}
	if args.TeamId != 0 {
		qv.Set("teamId", fmt.Sprintf("%d", args.TeamId))
	}
	if args.LeagueId != 0 {
		qv.Set("leagueId", fmt.Sprintf("%d", args.LeagueId))
	}
	if args.PersonId != 0 {
		qv.Set("personId", fmt.Sprintf("%d", args.PersonId))
	}
	if args.Limit != 0 {
		qv.Set("limit", fmt.Sprintf("%d", args.Limit))
	}
	if args.Offset != 0 {
		qv.Set("offset", fmt.Sprintf("%d", args.Offset))
	}
	if args.SortStat != "" {
		qv.Set("sortStat", args.SortStat)
	}
	if args.Order != "" {
		qv.Set("order", args.Order)
	}
	if args.Metrics != "" {
		qv.Set("metrics", args.Metrics)
	}
	if args.StartDate != "" {
		qv.Set("startDate", args.StartDate)
	}
	if args.EndDate != "" {
		qv.Set("endDate", args.EndDate)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_stats: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_stats: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_stats: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_stats: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getStatsStreaksArgs struct {
	StreakType string `json:"streakType"`
	StreakSpan string `json:"streakSpan"`
	Season     int    `json:"season"`
	SportId    int    `json:"sportId"`
	Limit      int    `json:"limit"`
	GameType   string `json:"gameType,omitempty"`
	Hydrate    string `json:"hydrate,omitempty"`
	Fields     string `json:"fields,omitempty"`
}

func (s *Server) toolGetStatsStreaks(ctx context.Context, _ *mcpsdk.CallToolRequest, args getStatsStreaksArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/stats/streaks"
	qv := url.Values{}
	if args.StreakType != "" {
		qv.Set("streakType", args.StreakType)
	}
	if args.StreakSpan != "" {
		qv.Set("streakSpan", args.StreakSpan)
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Limit != 0 {
		qv.Set("limit", fmt.Sprintf("%d", args.Limit))
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_stats_streaks: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_stats_streaks: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_stats_streaks: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_stats_streaks: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamAlumniArgs struct {
	TeamId  int    `json:"teamId"`
	Season  int    `json:"season"`
	Group   string `json:"group" jsonschema:"hitting | pitching | fielding"`
	Hydrate string `json:"hydrate,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamAlumni(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamAlumniArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/{teamId}/alumni"
	u = strings.Replace(u, "{teamId}", fmt.Sprintf("%d", args.TeamId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Group != "" {
		qv.Set("group", args.Group)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_alumni: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_alumni: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_alumni: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_team_alumni: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamCoachesArgs struct {
	TeamId int    `json:"teamId"`
	Season int    `json:"season,omitempty"`
	Date   string `json:"date,omitempty"`
	Fields string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamCoaches(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamCoachesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/{teamId}/coaches"
	u = strings.Replace(u, "{teamId}", fmt.Sprintf("%d", args.TeamId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Date != "" {
		qv.Set("date", args.Date)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_coaches: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_coaches: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_coaches: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_team_coaches: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamLeadersArgs struct {
	TeamId           int    `json:"teamId"`
	LeaderCategories string `json:"leaderCategories"`
	Season           int    `json:"season"`
	LeaderGameTypes  string `json:"leaderGameTypes,omitempty"`
	Hydrate          string `json:"hydrate,omitempty"`
	Limit            int    `json:"limit,omitempty"`
	Fields           string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamLeaders(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamLeadersArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/{teamId}/leaders"
	u = strings.Replace(u, "{teamId}", fmt.Sprintf("%d", args.TeamId), 1)
	qv := url.Values{}
	if args.LeaderCategories != "" {
		qv.Set("leaderCategories", args.LeaderCategories)
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.LeaderGameTypes != "" {
		qv.Set("leaderGameTypes", args.LeaderGameTypes)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Limit != 0 {
		qv.Set("limit", fmt.Sprintf("%d", args.Limit))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_leaders: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_leaders: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_leaders: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_team_leaders: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamPersonnelArgs struct {
	TeamId int    `json:"teamId"`
	Date   string `json:"date,omitempty"`
	Fields string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamPersonnel(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamPersonnelArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/{teamId}/personnel"
	u = strings.Replace(u, "{teamId}", fmt.Sprintf("%d", args.TeamId), 1)
	qv := url.Values{}
	if args.Date != "" {
		qv.Set("date", args.Date)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_personnel: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_personnel: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_personnel: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_team_personnel: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamStatsArgs struct {
	TeamId int    `json:"teamId"`
	Season int    `json:"season,omitempty"`
	Stats  string `json:"stats,omitempty" jsonschema:"e.g. season, byDateRange"`
	Group  string `json:"group,omitempty" jsonschema:"hitting | pitching | fielding"`
}

func (s *Server) toolGetTeamStats(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamStatsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/{teamId}/stats"
	u = strings.Replace(u, "{teamId}", fmt.Sprintf("%d", args.TeamId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Stats != "" {
		qv.Set("stats", args.Stats)
	}
	if args.Group != "" {
		qv.Set("group", args.Group)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_stats: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_stats: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_stats: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_team_stats: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamUniformsArgs struct {
	TeamIds string `json:"teamIds" jsonschema:"comma-separated team ids"`
	Season  int    `json:"season,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamUniforms(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamUniformsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/uniforms/team"
	qv := url.Values{}
	if args.TeamIds != "" {
		qv.Set("teamIds", args.TeamIds)
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_uniforms: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_uniforms: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_team_uniforms: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_team_uniforms: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamsArgs struct {
	Season       int    `json:"season,omitempty"`
	ActiveStatus string `json:"activeStatus,omitempty" jsonschema:"ACTIVE | INACTIVE | BOTH"`
	LeagueIds    string `json:"leagueIds,omitempty" jsonschema:"comma-separated league ids"`
	SportId      int    `json:"sportId,omitempty" jsonschema:"1 = MLB"`
	SportIds     string `json:"sportIds,omitempty" jsonschema:"comma-separated sport ids"`
	GameType     string `json:"gameType,omitempty" jsonschema:"R | S | E | A | D | F | L | W"`
	Hydrate      string `json:"hydrate,omitempty"`
	Fields       string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeams(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.ActiveStatus != "" {
		qv.Set("activeStatus", args.ActiveStatus)
	}
	if args.LeagueIds != "" {
		qv.Set("leagueIds", args.LeagueIds)
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.SportIds != "" {
		qv.Set("sportIds", args.SportIds)
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_teams: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamsAffiliatesArgs struct {
	TeamIds string `json:"teamIds" jsonschema:"comma-separated team ids"`
	SportId int    `json:"sportId,omitempty"`
	Season  int    `json:"season,omitempty"`
	Hydrate string `json:"hydrate,omitempty"`
	Fields  string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamsAffiliates(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamsAffiliatesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/affiliates"
	qv := url.Values{}
	if args.TeamIds != "" {
		qv.Set("teamIds", args.TeamIds)
	}
	if args.SportId != 0 {
		qv.Set("sportId", fmt.Sprintf("%d", args.SportId))
	}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_affiliates: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_affiliates: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_affiliates: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_teams_affiliates: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamsHistoryArgs struct {
	TeamIds     string `json:"teamIds" jsonschema:"comma-separated team ids"`
	StartSeason int    `json:"startSeason,omitempty"`
	EndSeason   int    `json:"endSeason,omitempty"`
	Fields      string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamsHistory(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamsHistoryArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/history"
	qv := url.Values{}
	if args.TeamIds != "" {
		qv.Set("teamIds", args.TeamIds)
	}
	if args.StartSeason != 0 {
		qv.Set("startSeason", fmt.Sprintf("%d", args.StartSeason))
	}
	if args.EndSeason != 0 {
		qv.Set("endSeason", fmt.Sprintf("%d", args.EndSeason))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_history: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_history: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_history: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_teams_history: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getTeamsStatsArgs struct {
	Season    int    `json:"season"`
	SportIds  string `json:"sportIds,omitempty"`
	Group     string `json:"group"`
	Stats     string `json:"stats"`
	GameType  string `json:"gameType,omitempty"`
	Order     string `json:"order,omitempty"`
	SortStat  string `json:"sortStat,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	EndDate   string `json:"endDate,omitempty"`
	Fields    string `json:"fields,omitempty"`
}

func (s *Server) toolGetTeamsStats(ctx context.Context, _ *mcpsdk.CallToolRequest, args getTeamsStatsArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/teams/stats"
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.SportIds != "" {
		qv.Set("sportIds", args.SportIds)
	}
	if args.Group != "" {
		qv.Set("group", args.Group)
	}
	if args.Stats != "" {
		qv.Set("stats", args.Stats)
	}
	if args.GameType != "" {
		qv.Set("gameType", args.GameType)
	}
	if args.Order != "" {
		qv.Set("order", args.Order)
	}
	if args.SortStat != "" {
		qv.Set("sortStat", args.SortStat)
	}
	if args.StartDate != "" {
		qv.Set("startDate", args.StartDate)
	}
	if args.EndDate != "" {
		qv.Set("endDate", args.EndDate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_stats: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_stats: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_teams_stats: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_teams_stats: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getUmpireGamesArgs struct {
	UmpireId int    `json:"umpireId"`
	Season   int    `json:"season"`
	Fields   string `json:"fields,omitempty"`
}

func (s *Server) toolGetUmpireGames(ctx context.Context, _ *mcpsdk.CallToolRequest, args getUmpireGamesArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/jobs/umpires/games/{umpireId}"
	u = strings.Replace(u, "{umpireId}", fmt.Sprintf("%d", args.UmpireId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_umpire_games: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_umpire_games: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_umpire_games: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_umpire_games: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}

type getVenueArgs struct {
	VenueId int    `json:"venueId"`
	Season  int    `json:"season,omitempty"`
	Hydrate string `json:"hydrate,omitempty" jsonschema:"comma-separated hydrate flags (e.g. location,fieldInfo,timezone)"`
	Fields  string `json:"fields,omitempty" jsonschema:"comma-separated field projection"`
}

func (s *Server) toolGetVenue(ctx context.Context, _ *mcpsdk.CallToolRequest, args getVenueArgs) (*mcpsdk.CallToolResult, any, error) {
	u := "https://statsapi.mlb.com/api/v1/venues/{venueId}"
	u = strings.Replace(u, "{venueId}", fmt.Sprintf("%d", args.VenueId), 1)
	qv := url.Values{}
	if args.Season != 0 {
		qv.Set("season", fmt.Sprintf("%d", args.Season))
	}
	if args.Hydrate != "" {
		qv.Set("hydrate", args.Hydrate)
	}
	if args.Fields != "" {
		qv.Set("fields", args.Fields)
	}
	if len(qv) > 0 {
		u += "?" + qv.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_venue: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_venue: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("mlb_get_venue: read body: %w", err)
	}
	if resp.StatusCode != 200 {
		return nil, nil, fmt.Errorf("mlb_get_venue: HTTP %d: %s", resp.StatusCode, string(body))
	}
	return textResult(string(body)), nil, nil
}
