// Copyright (c) 2026 John Dewey
//
// SPDX-License-Identifier: MIT

// Command mcpgen reads the mlb-sdk OpenAPI 3.0 spec and emits
// tools_gen.go — a generated Go file containing MCP tool
// registrations, args structs, and handler methods for every
// operation in the spec. Each GET operation becomes one tool an
// LLM agent can call through the MCP server.
//
// The generated handlers build URLs from the spec's path template
// and parameters, then make HTTP GET calls to statsapi.mlb.com
// and return the raw JSON response. This gives full API coverage
// without requiring a typed SDK method for each endpoint.
//
// Invoked via `go tool` from the parent mcp package's go:generate
// directive.
package main

import (
	"flag"
	"log"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/retr0h/mlb-sdk/pkg/api"
)

const (
	mcpsdkPkg = "github.com/modelcontextprotocol/go-sdk/mcp"
)

// composedOps lists operationIds already covered by hand-written
// composed tools — the generator skips these.
var composedOps = map[string]bool{
	"getSchedule":           true,
	"getBoxscore":           true,
	"getLinescore":          true,
	"getStandings":          true,
	"getTeam":               true,
	"getPerson":             true,
	"getFreeAgents":         true,
	"getTeamRoster":         true,
	"getTransactions":       true,
	"getStatsLeaders":       true,
	"getSchedulePostseason": true,
	"getStats":              true,
	"getDraft":              true,
}

func main() {
	out := flag.String("out", "tools_gen.go", "output Go file")
	flag.Parse()

	// Read the spec directly from the mlb-sdk embedded bytes —
	// no file copy or symlink needed.
	specBytes := api.OpenAPISpec()
	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromData(specBytes)
	if err != nil {
		log.Fatalf("mcpgen: parse embedded spec: %v", err)
	}

	ops := collectOps(doc)
	sort.Slice(ops, func(i, j int) bool {
		return ops[i].toolName < ops[j].toolName
	})

	if err := emit(*out, ops); err != nil {
		log.Fatalf("mcpgen: emit %s: %v", *out, err)
	}
	log.Printf("mcpgen: wrote %s — %d tools", *out, len(ops))
}

type op struct {
	operationID  string
	toolName     string
	pascalName   string
	description  string
	pathTemplate string
	params       []param
}

type param struct {
	name        string
	goName      string
	description string
	in          string // "path" | "query"
	typ         string // "string" | "int"
	required    bool
}

func collectOps(doc *openapi3.T) []op {
	var ops []op

	paths := make([]string, 0, len(doc.Paths.Map()))
	for p := range doc.Paths.Map() {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, path := range paths {
		item := doc.Paths.Map()[path]
		if item.Get == nil || item.Get.OperationID == "" {
			continue
		}
		oper := item.Get
		if composedOps[oper.OperationID] {
			continue
		}

		desc := oper.Summary
		if oper.Description != "" {
			desc = strings.TrimSpace(oper.Description)
		}

		o := op{
			operationID:  oper.OperationID,
			toolName:     "mlb_" + operationToSnake(oper.OperationID),
			pascalName:   toPascal(oper.OperationID),
			description:  desc,
			pathTemplate: path,
		}

		for _, pRef := range oper.Parameters {
			p := pRef.Value
			if p == nil {
				continue
			}
			typ := "string"
			if p.Schema != nil && p.Schema.Value != nil {
				st := p.Schema.Value.Type
				if st != nil && len(st.Slice()) > 0 {
					switch st.Slice()[0] {
					case "integer":
						typ = "int"
					case "number":
						typ = "float64"
					case "boolean":
						typ = "bool"
					}
				}
			}
			o.params = append(o.params, param{
				name:        p.Name,
				goName:      toPascal(p.Name),
				description: p.Description,
				in:          p.In,
				typ:         typ,
				required:    p.Required,
			})
		}

		ops = append(ops, o)
	}
	return ops
}

func emit(path string, ops []op) error {
	f := jen.NewFile("mcp")
	f.ImportAlias(mcpsdkPkg, "mcpsdk")
	f.HeaderComment("Code generated by mcpgen; DO NOT EDIT.")
	f.Line()

	// registerGeneratedTools
	f.Comment("registerGeneratedTools wires every spec-derived MCP tool onto s.mcp.")
	f.Comment("Called from registerTools() in tools.go.")
	f.Func().Params(jen.Id("s").Op("*").Id("Server")).Id("registerGeneratedTools").Params().Block(
		emitRegistrations(ops)...,
	)

	// Args structs and handlers
	for _, o := range ops {
		f.Line()
		emitArgsStruct(f, o)
		f.Line()
		emitHandler(f, o)
	}

	return f.Save(path)
}

func emitRegistrations(ops []op) []jen.Code {
	stmts := make([]jen.Code, 0, len(ops))
	for _, o := range ops {
		stmts = append(stmts, jen.Qual(mcpsdkPkg, "AddTool").Call(
			jen.Id("s").Dot("mcp"),
			jen.Op("&").Qual(mcpsdkPkg, "Tool").Values(jen.Dict{
				jen.Id("Name"):        jen.Lit(o.toolName),
				jen.Id("Description"): jen.Lit(o.description),
			}),
			jen.Id("s").Dot("tool"+o.pascalName),
		))
	}
	return stmts
}

func emitArgsStruct(f *jen.File, o op) {
	if len(o.params) == 0 {
		return
	}
	structName := lcFirst(o.pascalName) + "Args"
	fields := make([]jen.Code, 0, len(o.params))
	for _, p := range o.params {
		jsonTag := p.name
		if !p.required {
			jsonTag += ",omitempty"
		}
		goTyp := goType(p.typ)
		tags := map[string]string{"json": jsonTag, "jsonschema": p.description}
		fields = append(fields, jen.Id(p.goName).Add(goTyp).Tag(tags))
	}
	f.Type().Id(structName).Struct(fields...)
}

func emitHandler(f *jen.File, o op) {
	hasArgs := len(o.params) > 0
	argsType := jen.Struct()
	if hasArgs {
		argsType = jen.Id(lcFirst(o.pascalName) + "Args")
	}

	f.Func().Params(jen.Id("s").Op("*").Id("Server")).Id("tool"+o.pascalName).Params(
		jen.Id("ctx").Qual("context", "Context"),
		jen.Id("_").Op("*").Qual(mcpsdkPkg, "CallToolRequest"),
		jen.Id("args").Add(argsType),
	).Params(
		jen.Op("*").Qual(mcpsdkPkg, "CallToolResult"),
		jen.Any(),
		jen.Error(),
	).Block(
		handlerBody(o)...,
	)
}

func handlerBody(o op) []jen.Code {
	stmts := make([]jen.Code, 0, 16)

	// Build URL
	stmts = append(stmts, jen.Id("u").Op(":=").Lit("https://statsapi.mlb.com"+o.pathTemplate))

	// Replace path params
	for _, p := range o.params {
		if p.in != "path" {
			continue
		}
		if p.typ == "int" {
			stmts = append(stmts, jen.Id("u").Op("=").Qual("strings", "Replace").Call(
				jen.Id("u"),
				jen.Lit("{"+p.name+"}"),
				jen.Qual("fmt", "Sprintf").Call(jen.Lit("%d"), jen.Id("args").Dot(p.goName)),
				jen.Lit(1),
			))
		} else {
			stmts = append(stmts, jen.Id("u").Op("=").Qual("strings", "Replace").Call(
				jen.Id("u"),
				jen.Lit("{"+p.name+"}"),
				jen.Id("args").Dot(p.goName),
				jen.Lit(1),
			))
		}
	}

	// Build query string
	queryParams := []param{}
	for _, p := range o.params {
		if p.in == "query" {
			queryParams = append(queryParams, p)
		}
	}
	if len(queryParams) > 0 {
		stmts = append(
			stmts,
			jen.Id("qv").Op(":=").Qual("net/url", "Values").Values(),
		)
		for _, p := range queryParams {
			var zeroCheck *jen.Statement
			var valExpr *jen.Statement
			switch p.typ {
			case "int":
				zeroCheck = jen.Id("args").Dot(p.goName).Op("!=").Lit(0)
				valExpr = jen.Qual("fmt", "Sprintf").
					Call(jen.Lit("%d"), jen.Id("args").Dot(p.goName))
			case "float64":
				zeroCheck = jen.Id("args").Dot(p.goName).Op("!=").Lit(0)
				valExpr = jen.Qual("fmt", "Sprintf").
					Call(jen.Lit("%g"), jen.Id("args").Dot(p.goName))
			case "bool":
				zeroCheck = jen.Id("args").Dot(p.goName)
				valExpr = jen.Lit("true")
			default:
				zeroCheck = jen.Id("args").Dot(p.goName).Op("!=").Lit("")
				valExpr = jen.Id("args").Dot(p.goName)
			}
			stmts = append(stmts, jen.If(zeroCheck).Block(
				jen.Id("qv").Dot("Set").Call(jen.Lit(p.name), valExpr),
			))
		}
		stmts = append(stmts, jen.If(jen.Len(jen.Id("qv")).Op(">").Lit(0)).Block(
			jen.Id("u").Op("+=").Lit("?").Op("+").Id("qv").Dot("Encode").Call(),
		))
	}

	// HTTP request
	errfn := func(msg string, extra ...jen.Code) jen.Code {
		args := make([]jen.Code, 0, 1+len(extra))
		args = append(args, jen.Lit(msg))
		args = append(args, extra...)
		return jen.Return(jen.Nil(), jen.Nil(), jen.Qual("fmt", "Errorf").Call(args...))
	}

	stmts = append(
		stmts,
		jen.List(jen.Id("req"), jen.Err()).Op(":=").Qual("net/http", "NewRequestWithContext").Call(
			jen.Id("ctx"), jen.Qual("net/http", "MethodGet"), jen.Id("u"), jen.Nil(),
		),
		jen.If(jen.Err().Op("!=").Nil()).Block(
			errfn(o.toolName+": %w", jen.Err()),
		),
		jen.List(jen.Id("resp"), jen.Err()).
			Op(":=").
			Qual("net/http", "DefaultClient").
			Dot("Do").
			Call(jen.Id("req")),
		jen.If(jen.Err().Op("!=").Nil()).Block(
			errfn(o.toolName+": %w", jen.Err()),
		),
		jen.Defer().Id("resp").Dot("Body").Dot("Close").Call(),
		jen.List(jen.Id("body"), jen.Err()).
			Op(":=").
			Qual("io", "ReadAll").
			Call(jen.Id("resp").Dot("Body")),
		jen.If(jen.Err().Op("!=").Nil()).Block(
			errfn(o.toolName+": read body: %w", jen.Err()),
		),
		jen.If(jen.Id("resp").Dot("StatusCode").Op("!=").Lit(200)).Block(
			errfn(
				o.toolName+": HTTP %d: %s",
				jen.Id("resp").Dot("StatusCode"),
				jen.String().Call(jen.Id("body")),
			),
		),
		jen.Return(
			jen.Id("textResult").Call(jen.String().Call(jen.Id("body"))),
			jen.Nil(),
			jen.Nil(),
		),
	)

	return stmts
}

func goType(typ string) jen.Code {
	switch typ {
	case "int":
		return jen.Int()
	case "float64":
		return jen.Float64()
	case "bool":
		return jen.Bool()
	default:
		return jen.String()
	}
}

func operationToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func toPascal(s string) string {
	segments := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_'
	})
	parts := make([]string, 0, len(segments))
	for _, seg := range segments {
		if seg == "" {
			continue
		}
		parts = append(parts, strings.ToUpper(seg[:1])+seg[1:])
	}
	return strings.Join(parts, "")
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
